### ISSUE TITLE
WheelPropagation Default Value

### ISSUE THREAD

**Issue by onlysolace** [mdbootstrap/perfect-scrollbar#856] opened 2019-03-27 15:34 UTC
The default value for wheel propagation appears to be true. I had to explicitly define wheelPropagation to be false in order to prevent the custom scrollbar from scrolling the main page scrollbar.

**Comment by apriljunge** [comment] 2019-05-29 18:02
Duplicate of #826

**Closed** 2020-01-16 12:44 UTC
