### ISSUE TITLE
Scroll bars not working on touch screens in chrome

### ISSUE THREAD

**Issue by HIMISOCOOL** [mdbootstrap/perfect-scrollbar#845] opened 2019-01-18 03:01 UTC
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] Check [FAQ](https://github.com/utatti/perfect-scrollbar/wiki/FAQ) and [Caveats](https://github.com/utatti/perfect-scrollbar/wiki/Caveats)
- [x] Search if there's already one reported in Issues
- [x] Prepare a JSFiddle reproducing the issue
  - [perfect-scrollbar JSFiddle](https://jsfiddle.net/utatti/dyvL31r6/)

Hey there guys, I cannot get perfect scroll to work on touch screen in chrome.

It works fine in Edge and Firefox and mouse scroll works in Chrome so I'm pretty sure I have it setup correctly, I just tried with the base jsfiddle you guys provide and it behaves the same as what I'm seeing

**Comment by PhilippS93** [comment] 2019-04-04 11:22
It is also not working for me.

**Comment by muslim-niche** [comment] 2019-05-09 12:00
Not working in chrome on touch laptop

**Comment by apriljunge** [comment] 2019-05-29 17:59
Duplicate of #867

**Comment by mattonit** [comment] 2020-01-16 12:39
This was fixed in the latest release

**Closed by mattonit** 2020-01-16 12:39 UTC
